import turtle as t
t.speed(0)
def leaves(x,y):
    t.penup()
    t.goto(x,y)
    t.pendown()
    t.setheading(0)
    t.color('green')
    t.begin_fill()
    t.forward(120)
    t.left(120)
    t.forward(120)
    t.left(120)
    t.forward(120)
    t.left(120)
    t.end_fill()
def trunk(x,y):
    t.penup()
    t.goto(x,y)
    t.pendown()
    t.color('sienna')
    t.begin_fill()
    t.setheading
    t.forward(30)
    t.right(90)
    t.forward(90)
    t.right(90)
    t.forward(30)
    t.right(90)
    t.forward(90)
    t.right(90)
    t.end_fill()

leaves(-60,60)
leaves(-60,0)
leaves(-60,-60)
trunk(-15,-60)